export const ACT_CINEMA_TABLE_REQUEST = 'CinemaTableReducer/ACT_CINEMA_TABLE_REQUEST';
export const ACT_CINEMA_TABLE_SUCCESS = 'CinemaTableReducer/ACT_CINEMA_TABLE_SUCCESS';
export const ACT_CINEMA_TABLE_FAILED = 'CinemaTableReducer/ACT_CINEMA_TABLE_FAILED';

