export const ACT_MOVIE_SCHEDULE_REQUEST = 'scheduleReducer/ACT_MOVIE_SCHEDULE_REQUEST';
export const ACT_MOVIE_SCHEDULE_SUCCESS = 'scheduleReducer/ACT_MOVIE_SCHEDULE_SUCCESS';
export const ACT_MOVIE_SCHEDULE_FAILED = 'scheduleReducer/ACT_MOVIE_SCHEDULE_FAILED';
